### PR TITLE
Sweet Badges

### PR DESCRIPTION
**Pull request by jarsen**
Adds some shields to the readme

### CODE REVIEW

**Comment by brianmullen** [comment]
Why does our license say its copyrighted by `Rob Rix`? and `2014`?

**Comment by jarsen** [comment]
@psychoticidiot cuz I copied it out of `antitypical/Result` :see_no_evil:

**Comment by brianmullen** [comment]
Do we want a copyright in there for the `utahiosmac` group? It might help advertise our community.

**Comment by jarsen** [comment]
That's a fair idea. I don't know that anyone will actually read that though, especially if they're getting it from `utahiosmac/Marshal` anyway. But let's do it.

**Comment by brianmullen** [comment]
I will probably be forking this repo after we get it in a stable state. I have a lot of extensions that probably won't go into the core. For that reason, if people get my version of it, the copyright will still advertise the community.

**Pull request merged**
