### PR TITLE
add support for MarshaledArray.

### PR DESCRIPTION
**Pull request by brianmullen**
This adds support for marshalling/unmarshalling values from an array. This will be beneficial for the other top level object in JSON parsing.

### CODE REVIEW

**Comment by jarsen** [comment]
Interesting. Do you run into this often?

**Comment by brianmullen** [comment]
I don't run into this because the JSON that I work with is usually by my own design. However, we need to decide what this library is. 

Are we a JSON library? If so, we should support the valid structures supported by JSON and not just pick and choose because that is what we commonly use.

**Comment by brianmullen** [comment]
This PR might be pointless if we are moving to a protocol as the base. As we could just add the protocol to an array directly if needed.

**Comment by jarsen** [comment]
It seems so to me. Should we close?

**Comment by brianmullen** [comment]
I think with using a protocol this would become really easy for anyone to implement this behavior and so I think there is no need to include this with the framework so we can keep it focused.

**Pull request closed without merging**
