### PR TITLE
Add initial podspec.

### PR DESCRIPTION
**Pull request by brianmullen**
This adds the initial podspec for cocoapod support.

### CODE REVIEW

**Comment by brianmullen** [comment]
This is for issue #6

**Comment by brianmullen** [comment]
It looks like this pull request is triggering an automated build but it fails because no travis.yml file is found. We will need to run the tests again once the pull request #41 has been merged.

**Comment by brianmullen** [comment]
The podspec will need to be adjusted after PR #43 has been merged.

**Comment by brianmullen** [comment]
@jarsen @bwhiteley This branch is ready to be merged. We should increment the release tag to 0.9.2 (after this is merged), because of the source file path changes, and afterwards I will push the podspec to the central repo to make it public.

**Comment by jarsen** [comment]
Ok. Have the changes necessary after #43 been made?

**Comment by jarsen** [comment]
I'm assuming so. Here it goes.

**Comment by brianmullen** [comment]
@jarsen Yes, the changes were made.

**Pull request merged**
