### PR TITLE
Use Swift `Int` for extracting `Int64` by default instead of `NSNumber`

### PR DESCRIPTION
**Pull request by brianmullen**
This favors using Swift's builtin Int support instead of bridging back and forth with NSNumber.

### CODE REVIEW

**Comment by brianmullen** [comment]
#12

**Comment by bwhiteley** [comment]
@psychoticidiot does this work on 32bit platforms?

**Comment by brianmullen** [comment]
I cant say I tested that. However, the NSNumber.longLongValue is just an alias to `long long` in `c` which is platform dependent on how they handle that. I am just assuming that the Swift guys handled the `Int` in the same way as NSNumber for 32 bit platforms.

**Comment by brianmullen** [comment]
@bwhiteley it looks like Int64 doesn't work on 32bit platforms but NSNumber does. 

Do we want to always use NSNumber? Or do we want to put in logic so that 32bit uses NSNumber and 64bit uses Int? Or do we not support 32bit?

We should be able to test for 64bit using something like `let is64Bit = sizeof(Int) == sizeof(Int64)`

**Comment by bwhiteley** [comment]
What's wrong with leaving it the way it was?

**Comment by brianmullen** [comment]
It doesn't feel very Swift-like using `NSNumber`. Although, it seems like using `NSNumber` is the best thing for 32bit platforms, but aren't those considered legacy platforms? 

I think we should support it, but it should be fallback code that supports legacy platforms and not have our primary code support all platforms.

We already have existing code that we chose to do it the Swift-way instead of bridging to obj-c and so it feels like we would be inconsistent if we leave it the way it is. The code I am referencing is `key.stringValue.characters.split(".").map(String.init)`...we easily could have just did a bridge to `NSString` but we chose not too.

**Comment by derrh** [comment]
I'm in favor of leaving this the way it was. At least in the case of JSON parsed via `NSJSONSerialization` the values in the dictionaries will be `NSNumber`s already. Are we worried about performance?

Parsing via NSNumber seems more correct and simplifies the code vs checking word size.

**Comment by brianmullen** [comment]
If I define a native Swift Dictionary it wont be the case where it will always be an `NSNumber`. We are making the core of this library generic so that users can extend this (or we can) to include other data formats. Yes, parsing it via `NSJONSerialization` will be an `NSNumber` but that wont be the case for all data formats.

I am not saying that checking the word size is optimal either. I just think since we are a Swift library that we should try to do it the "Swift" way before falling back to bridging. If we make an exception for `NSNumber` then we will need to make exceptions for other data types that aren't native to Swift.

**Comment by jarsen** [comment]
I think that's a good point: we can no longer expect that all the `MarshaledObject`s will be coming out of `NSJSONSerialization`.

**Comment by brianmullen** [comment]
This is a non-issue. 

There is a no way an `Int64` can be inside of a `MarshaledObject` (values can only be `AnyObject`) and so the only way the native `Int64` would work is if you manually call the `value` method on another source.

**Comment by derrh** [comment]
@psychoticidiot, that's true of `Int` and `Bool` as well. They are all boxed in `NSNumber`s. Implementation doesn't matter so much to me so long as we support `Int64`.

**Comment by brianmullen** [comment]
I am closing this pull request as the decision was to keep this library defined as `[String: AnyObject]` and so supporting native swift types wont be needed.

**Pull request closed without merging**
