### PR TITLE
Remove keytype

### PR DESCRIPTION
**Pull request by brianmullen**
This removes the KeyType protocol in favor of the Swift 3 builtin AnyHashable.

### CODE REVIEW

**Comment by jgrandelli** [comment]
Nice update!

**Comment by bwhiteley** [comment]
This change causes a 2x performance regression.

**Comment by brianmullen** [comment]
Not sure why the default swift3 bridging of a `NSDictionary` to `[AnyHashable: Any]` is not very performant.

I am going to close this PR because this offers no additional benefit (a consumer can make `AnyHashable` or whatever is needed conform to `KeyType`) but just causes a performance loss.

**Comment by jarsen** [comment]
We should still remove the .orig files though in a separate PR... 😬 @psychoticidiot

**Pull request closed without merging**
